# fly.toml app configuration file generated for event-captioner-slackbot on 2023-08-16T14:51:21-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "event-captioner-slackbot"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 0
  processes = ["app"]
